microblog/blog/models.py
from django.db import models
from django.db.models.signals import post_save
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager
from django.dispatch import receiver
from .exeption_models import BaseManager


class Tag(models.Model):
    """ タグ """
    objects = BaseManager()
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Blog(models.Model):
    """ ポスト"""
    content = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='anicolleblog', blank=True, null=True)
    posted_date = models.DateTimeField(auto_now_add=True)
    tag = models.ManyToManyField(Tag, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_num = models.IntegerField(default=0)

    class Meta:
        ordering = ['-posted_date']

    def __str__(self):
        return self.content


class Comment(models.Model):
    """ コメント """
    content = models.TextField('コメント')
    post = models.ForeignKey(Blog, verbose_name='対象記事', on_delete=models.CASCADE)
    # selfはForrignKey(Comment)を意味する。
    parent = models.ForeignKey('self', verbose_name='親コメント', null=True, blank=True, on_delete=models.CASCADE)
    commented_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content


class Like(models.Model):
    """ いいね """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name='like_user')
    post = models.ForeignKey(Blog, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user


class UserProfile(models.Model):
    """ ユーザープロフィール """
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                related_name='profile')
    picture = models.ImageField(upload_to='profile_pictures', blank=True, null=True,)
    bio = models.TextField(blank=True)

    def __str__(self):
        return self.user.username


class UserManager(BaseUserManager):
    """ユーザーマネージャー."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """メールアドレスでの登録を必須にする"""
        if not email:
            raise ValueError('メールアドレスを入力してください')
        email = self.normalize_email(email)

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """is_staff(管理サイトにログインできるか)と、is_superuer(全ての権限)をFalseに"""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """スーパーユーザーは、is_staffとis_superuserをTrueに"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""

    email = models.EmailField(_('email address'), unique=True)
    nick_name = models.CharField(_('nick name'), max_length=50, blank=False, unique=True, db_column="ユーザー名")

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_short_name(self):
        return self.nick_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """ユーザーにメールを送る"""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def username(self):
        """username属性のゲッター

        他アプリケーションが、username属性にアクセスした場合に備えて定義
        メールアドレスを返す
        """
        return self.email


@receiver(post_save, sender=User)
def create_profile(sender, **kwargs):
    """ 新ユーザー作成時に空のprofileも作成する """
    if kwargs['created']:
        user_profile = UserProfile.objects.get_or_create(user=kwargs['instance'])

microblog/blog/views/anime_search_view.py
from django.shortcuts import render
from blog.forms import SearchForm
from blog.views import blog_option_view
import requests


# アニメ検索機能（関数ビューの知見）
def api_call(request):
    endpoint = 'http://api.moemoe.tokyo/anime/v1/master'

    # リクエストがpostであることをチェック
    if request.method == 'POST':
        # フォームデータを取得
        form = SearchForm(request.POST)
        # フォームのデータが安全かチェック
        if form.is_valid():

            # データを受け取る
            year = form.cleaned_data['year']
            cours = form.cleaned_data['cours']

            if year:
                query = str(year)
                url = endpoint + "/" + query

            else:
                form = SearchForm()
                messages = ["放送年を選択してください"]
                context = {'messages': messages, 'form': form}

                return render(request, 'blog/anime_search.html', context)

            if cours:
                query = str(cours)
                url = url + "/" + query

            response = requests.get(url)
            anime_list = response.json()

            form = SearchForm()

            page_obj = blog_option_view.paginate_queryset(request, anime_list, 10)
            context = {
                'anime_list': page_obj.object_list,
                'form': form,
                'year': year,
                'cours': cours,
                'page_obj': page_obj,
            }

            return render(request, 'blog/anime_search.html', context)

        else:
            form = SearchForm()
            messages = ["放送年を選択してください"]

            context = {'messages': messages, 'form': form}

            return render(request, 'blog/anime_search.html', context)
    else:

        # 最初にブラウザから呼び出されるときに使用するフォームクラスを指定
        form = SearchForm()

        # ページネーションバーからGETで遷移したときの処理
        # ページネーションしてきたときはクエリにyear,coursがあるのでそれを判定して分岐に入る
        if 'year' in request.GET:
            year = request.GET.get('year')
            url = endpoint + "/" + year

            cours = request.GET.get('cours')

            if cours:
                cours = request.GET.get('cours')
                url = url + "/" + cours

            response = requests.get(url)
            anime_list = response.json()
            page_obj = blog_option_view.paginate_queryset(request, anime_list, 10)

            context = {
                'anime_list': page_obj.object_list,
                'form': form,
                'year': year,
                'cours': cours,
                'page_obj': page_obj,
            }

            return render(request, 'blog/anime_search.html', context)

    # 作成されたフォームオブジェクトをコンテキストへ格納
    context = {'form': form}
    # 最初にブラウザから呼び出されたときに指定テンプレートとコンテキストで描画する
    return render(request, 'blog/anime_search.html', context)

microblog/blog/views/blog_view.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from blog.models import Blog, Like, Tag
from blog.forms import BlogForm, TagInlineFormSet
import re

User = get_user_model()


class BlogListView(ListView):
    model = Blog
    # レスポンスに込めるobjectの名前を変える
    context_object_name = "blog_list"
    paginate_by = 10


class BlogByTagList(ListView):
    model = Blog
    context_object_name = "blog_list"
    paginate_by = 10
    slug_field = "tag"
    slug_url_kwarg = "tag"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag = Tag.objects.get_or_none(name=self.kwargs['tag'])

        if not tag:
            messages.error(self.request, str("タグに「" + self.kwargs['tag'] + "」がつく投稿はありません"))
            context['blog_list'] = Blog.objects.all()
            return context

        context['blog_list'] = Blog.objects.filter(tag=tag)
        context['tag'] = tag
        return context


class BlogDetailView(DetailView):
    model = Blog

    def get_context_data(self, **kwargs):
        # 継承元のメソッドを呼び出す
        context = super().get_context_data(**kwargs)
        # 記事へのコメントを取得
        context['comment_list'] = self.object.comment_set.filter(parent__isnull=True)
        tags = self.object.tag.filter(blog=kwargs['object'])
        tag_list = []

        for tag in tags:
            tag_list.append(str(tag.name))

        context['tags'] = tag_list
        context['like_cnt'] = Like.objects.filter(post=kwargs['object']).count()
        return context


class BlogCreateView(LoginRequiredMixin, CreateView):
    # modelのfieldsはformClassに任せる
    model = Blog
    form_class = BlogForm
    # LoginRequiredMixinを使う際は定義する必要あり
    login_url = '/login'

    success_url = reverse_lazy("index")
    # templateをクラス汎用ビューのデフォルトから変える
    template_name = "blog/blog_create_form.html"

    def get_context_data(self, **kwargs):
        context = super(BlogCreateView, self).get_context_data(**kwargs)
        context.update(dict(formset=TagInlineFormSet(self.request.POST or None, instance=self.object)))

        return context

    # バリデート後
    def form_valid(self, form):

        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            tags = self.request.POST.get("tag")
            tag_list = re.split("[,、]", tags)

            blog = form.save(commit=False)
            blog.save()

            for tag in tag_list:
                tag = tag.strip()
                if tag != "":
                    exists_tag = Tag.objects.get_or_none(name=tag)

                    if exists_tag:
                        blog.tag.add(exists_tag)
                    else:
                        tag_obj = Tag(name=tag)
                        tag_obj.save()
                        blog.tag.add(tag_obj)

            messages.success(self.request, "保存しました。")
            return super().form_valid(form)

        else:
            context['form'] = form
            messages.error(self.request, "保存に失敗しました。")
            return self.render_to_response(context)

    def form_invalid(self, form):
        # self.requestオブジェクトに”保存に失敗しました。”を込める
        messages.error(self.request, "保存に失敗しました。")
        return super().form_invalid(form)


class BlogByAnimeCreateView(BlogCreateView):
    slug_field = "anime"
    slug_url_kwarg = "anime"

    def get_context_data(self, **kwargs):
        context = super(BlogByAnimeCreateView, self).get_context_data(**kwargs)
        context.update(dict(formset=TagInlineFormSet(self.request.POST or None, instance=self.object)))
        return context

    def get_initial(self):
        initial = super().get_initial()
        initial["tag"] = self.kwargs['anime']
        return initial


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm

    login_url = '/login'

    def get_context_data(self, **kwargs):
        context = super(BlogUpdateView, self).get_context_data(**kwargs)
        context.update(dict(formset=TagInlineFormSet(self.request.POST or None, instance=self.object)))
        tags = self.object.tag.filter(**kwargs)
        tag_list = []

        for tag in tags:
            tag_list.append(str(tag.name))

        context['tags'] = tag_list
        return context

    def get_initial(self):
        initial = super().get_initial()
        tags = self.object.tag.filter(blog=self.kwargs['pk'])
        tag_list = (','.join([str(tag) for tag in tags]))

        initial["tag"] = tag_list
        return initial

    # success_urlを自作する
    def get_success_url(self):
        # <int:pk>はself.kwargsに{"pk": 2（int）}と辞書型にセットされているためpkを取得する
        blog_pk = self.kwargs['pk']

        # 上記同様にreverseする際も{"pk": blog_pk}の辞書型形式でkwargsにセットしてあげる
        url = reverse_lazy("detail", kwargs={"pk": blog_pk})
        return url

    # templateをクラス汎用ビューのデフォルトから変える
    template_name = "blog/blog_update_form.html"

    # バリデート後
    def form_valid(self, form):

        tags = self.request.POST.get("tag")
        tag_list = re.split("[,、]", tags)

        blog = form.save(commit=False)
        blog.save()

        if not tags:
            messages.success(self.request, "更新しました。")
            return super().form_valid(form)

        blog.tag.clear()

        for tag in tag_list:
            tag = tag.strip()
            if tag != "":
                exists_tag = Tag.objects.get_or_none(name=tag)

                if exists_tag:
                    blog.tag.add(exists_tag)
                else:
                    tag_obj = Tag(name=tag)
                    tag_obj.save()
                    blog.tag.add(tag_obj)

        messages.success(self.request, "更新しました。")
        return super().form_valid(form)

    def form_invalid(self, form):
        # self.requestオブジェクトに”更新に失敗しました。”を込める
        messages.error(self.request, "更新に失敗しました。")
        return super().form_invalid(form)


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    # LoginRequiredMixinを先に継承しないとエラーになることがある

    model = Blog
    success_url = reverse_lazy("index")

    # LoginRequiredMixinを使う際は定義する必要あり
    login_url = '/login'

    # バリデート後
    def delete(self, request, *args, **kwargs):
        # self.requestオブジェクトに”削除しました。”を込める
        messages.success(self.request, "削除しました。")
        # super()で継承元の処理を返すのがお約束
        return super().delete(request, *args, **kwargs)



microblog/blog/templates/blog/anime_search.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block body %}
<h1>アニメを探す</h1>
<div class="post-preview">
    <p class="post-meta">
        アニメに関する投稿を探したり、タグ付け投稿したりできます。
    </p>
</div>
<form action="{% url 'search' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table">
        <div class="form-group row">
            <div class="col-sm-3">
                {{ form.year.label }}
                {{ form.year|add_class:'form-control' }}
            </div>
            <div class="col-sm-3">
                {{ form.cours.label }}
                {{ form.cours|add_class:'form-control' }}
            </div>
        </div>
    </table>
    <div class="form-group row">
        <div class="col-sm">
            <button type="submit" class="btn btn-primary btn-block" name='action' value="search">アニメを探す</button>
        </div>
    </div>
</form>
<br>
{% if anime_list %}
{% for anime in anime_list %}
<blockquote class="blockquote">
    <div class="row">
        <div class="col-md-12">
            <h4>{{ anime.title }}</h4>
        </div>
    </div>
    <div class="btn-group" role="group">
        <a href= "{% url 'tag_seach' anime.title  %}" class="btn btn-secondary btn-default">
            <div class="post-preview">
                <div class="post-meta">投稿を探す</div>
            </div>
        </a>
        <a href= "{% url 'create_by_anime' anime.title%}" class="btn btn-secondary btn-default">
            <div class="post-preview">
                <div class="post-meta">投稿をする</div>
            </div>
        </a>
    </div>
</blockquote>
{% endfor%}
{% if anime_list %}
<nav aria-label="Page navigation">
    <ul class="pagination">
        <!-- 前へ の部分 -->
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link"
               href="?page={{ page_obj.previous_page_number }}&year={{ year }}&cours={{ cours }}">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% endif %}

        <!-- 数字の部分 -->
        {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link"
                                 href="?page={{ num }}&year={{ year }}&cours={{ cours }}">{{ num }}</a></li>
        {% endif %}
        {% endfor %}

        <!-- 次へ の部分 -->
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link"
               href="?page={{ page_obj.next_page_number }}&year={{ year }}&cours={{ cours }}">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

{% endif %}
{% endblock %}

microblog/blog/templates/blog/blog_confirm_delete.html
{% extends "base.html" %}

{% block body %}
        <h1>削除確認</h1>

        <p class="text text-danger">削除してよろしいですか？</p>

        <form method="post">
            <table class="table">
                {% csrf_token %}
                {{ form }}
            </table>
            <button class="btn btn-danger" type="submit">削除する</button>
            <a href="{% url 'detail' blog.id %}" class="btn btn-defult">やめる</a>
        </form>
{% endblock %}

microblog/blog/templates/blog/blog_create_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block body %}
<h1>新規作成</h1>
<form method="post" enctype="multipart/form-data">
    <div class="form-group row ">
        {% csrf_token %}
        {{ formset.management_form }}
        <input type="hidden" name="user" id="id_user" value="{{ user.id }}">
        <div class="form-group">
            {{ form.content.label }}:
            {{ form.content|add_class:'form-control' }}
        </div>
        <div class="form-group">
            {{ form.photo.label }}:
            {{ form.photo|add_class:'form-control' }}
        </div>
        <div class="form-group">
            {{ form.tag.label }}:
            {{ form.tag|add_class:'form-control' }}
            <div class="small">※カンマ(全角半角)区切りで書いてください</div>
        </div>
    </div>
    <hr>
    <div class="form-group row">
        <div class="col-sm">
            <button type="submit" class="btn btn-info btn-block">保存する</button>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm">
            <a href="{% url 'index' %}" class="btn btn-default btn-block">戻る</a>
        </div>
    </div>
</form>
{% endblock %}

microblog/blog/templates/blog/blog_detail.html
{% extends "base.html" %}
{% load static %}
{% block body %}

<head>
    <script>
        function api_like() {
            var api_url = "{% url 'api_like' object.pk %}";
            var btn = document.getElementById("like");
            var request = new XMLHttpRequest();
            request.onreadystatechange = function () {
                if (request.readyState === 4 && request.status === 200) {
                    var received_data = JSON.parse(request.responseText);
                    btn.innerText = received_data.like;
                }
            }
            request.open("GET",api_url);
            request.send();
        }


    </script>
</head>
{# {% %}　プログラム的な命令 #}
{# {{ }}　値の表示 #}
{# object==データが入っている変数、デフォルト値 #}

<div class="post-preview">
    <div class="row">
        <div class="col-xs-12">
            {% if tags %}
            タグ:
            {% for tag in tags %}
            <a href="{% url 'tag_seach' tag %}" class="btn-gradient-radius">{{ tag }}</a>
            {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-sm-7">
            <h3 class="post-title">
                <a href="{% url 'profile_detail' object.user.nick_name %}" class="small">@{{object.user.nick_name}}</a>
                <br>
                {{object.content}}
            </h3>
            <br>
        </div>
        {% if object.photo %}
        <div class="col-sm-5">
            <p>
            <img src="{{ object.photo.url }}" class="img-responsive"><br>
            </p>
        </div>
        {% endif %}
    </div>
</div>
<div class="post-meta row">

    <div class="col-xs-12">
        {{object.posted_date|date:"Y/m/d h:m:s"}}
    </div>
    <div class="col-md-10 col-sm-9 col-xs-7">
        <a onclick="api_like()" class="btn-gradient-radius"><span id="like">{{ like_cnt }} </span>いいね！</a>
    </div>

    <div class="col-md-2 col-sm-3 col-xs-5 small">
        {% if user.is_authenticated and user.id == object.user.id%}
        <a href="{% url 'update' object.id %}">編集</a>
        /
        <a href="{% url 'delete' object.id %}">削除</a>
        {% endif %}
    </div>

</div>
<br>
{% if not user.is_authenticated %}
<p class="post-meta">※いいね機能を使うにはログインしてください</p>
{% endif %}
<div class="form-group row">
    <a href="{% url 'comment_create' object.pk %}" class="btn btn-info btn-block">コメントする</a>
</div>
<div class="form-group row">
    <div class="col-sm">
        <a href="{% url 'index' %}" class="btn btn-default btn-block">戻る</a>
    </div>
</div>
<hr>
<h4 class="title is-5">コメント一覧</h4>
{% for comment in comment_list %}
<div class="post-preview">
    <div class="post-meta">

        {{ comment.content }}
        <div class="pull-right ">
            <small>{{ comment.commented_date }}</small>
        </div>
    </div>
    <br>
    <a href="{% url 'reply_create' comment.pk %}" class="btn">返信する</a>
    {% with reply_list=comment.comment_set.all %}
    {% include 'blog/includes/reply.html' %}
    {% endwith %}
</div>
</div>
{% endfor %}
{% endblock %}

microblog/blog/templates/blog/blog_list.html
{% extends "base.html" %}

{% block body %}
{% if not user.is_authenticated %}

<div class="post-preview">

    <h3 class="post-title">
        使い方
    </h3>

    <p class="post-meta">メニューバーにある”SIGNUP”からユーザー登録してください。<br>
        自分用の簡単な独り言ブログが使用できるようになります。<br>
        TEST用のユーザーも用意してるので試してみてください。<br>
        ＜TEST用ユーザー＞<br>
        email:test@gmail.com<br>
        password:testzaq1zaq1<br>
    </p>


</div>

{% endif %}

{% if user.is_authenticated %}
    <a href="{% url 'create' %}" class="btn btn-primary">投稿する</a>
{% endif %}
<br>
<br>
{% if tag %}
    <div>
    タグに<a href="{% url 'tag_seach' tag %}" class="btn-gradient-radius">{{ tag }}</a>が付いた投稿
    </div>
{% endif %}
<br>
{# {% %}　プログラム的な命令 #}
{# {{ }}　値の表示 #}
{# object_listという変数名はListViewで定義されているので、固定 Viewで指定すれば変更もできる #}
{% for blog in blog_list %}
<blockquote class="blockquote">
<div class="post-preview">
    <a href="{% url 'detail' blog.id %}">
        <h3 class="post-meta">
            {{blog.content}}
        </h3>
        {% if blog.photo %}
        <p class="post-subtitle">※画像あり</p>
        {% endif %}

    </a>

    {# timesinceは”|”で渡されたdateから現在までを計算するDjangoの組み込み関数 #}
    <p class="post-meta">
        <b><a href="{% url 'profile_detail' blog.user.nick_name %}">@{{blog.user.nick_name}}</a>
        </b> ｜ {{blog.posted_date}} ｜投稿から {{blog.posted_date|timesince}}
    </p>
</div>
</blockquote>
{% endfor %}


{% if is_paginated %}
<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li>
            <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span></a>
        </li>
        {% endif %}

        {% for page in paginator.page_range %}
        <li {% if page == page_obj.number %} class="active" {% endif %}>
            <a href="?page={{ page }}">{{ page }}</a>
        </li>
        {% endfor %}

        {% if page_obj.has_next %}
        <li>
            <a href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span></a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

{% endblock %}

microblog/blog/templates/blog/blog_update_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block body %}
<h1>編集</h1>
<form method="post" enctype="multipart/form-data">
    <div class="form-group row">
        {% csrf_token %}
        {{ formset.management_form }}
        <input type="hidden" name="user" id="id_user" value="{{ user.id }}">
        <div class="form-group">
            {{ form.content.label }}:
            {{ form.content|add_class:'form-control' }}
        </div>
        <div class="form-group">
            {{ form.photo.label }}:
            {{ form.photo|add_class:'form-control' }}
        </div>
        <div class="form-group">
            {{ form.tag.label }}:
            {{ form.tag|add_class:'form-control' }}
            <div class="small">※空欄の場合は更新されません。</div>
        </div>
    </div>
    <hr>
    <div class="form-group row">
        <div class="col-sm">
            <button type="submit" class="btn btn-info btn-block">保存する</button>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm">
            <a href="{% url 'detail' object.id %}" class="btn btn-warning btn-block">やめる</a>
        </div>
    </div>
</form>
{% endblock %}

microblog/blog/templates/blog/comment_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    <div class="form-group row">
        <div class="form-group">
            <div class="col-sm">
                {% csrf_token %}
                {{ form.content.label }}:
                {{ form.content|add_class:'form-control' }}
            </div>
        </div>
        <hr>
        <div class="form-group">
            <div class="col-sm">
                <button type="submit" class="btn btn-info btn-block">コメントする</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

microblog/blog/templates/blog/profile_detail.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
            <h3>
                プロフィール
            </h3>
            <div class="row">
                <div class="col-md-5">
                    {% if object.picture %}
                    <img src="{{ object.picture.url }}" class="img-circle img-responsive">
                    {% else %}
                    ※画像無
                    {% endif %}
                </div>
                <div class="col-md-7">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <b>
                                ユーザー名
                            </b>
                        </div>
                        <div class="panel-body">
                            {{ object.user.nick_name }}
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <b>
                                紹介文
                            </b>
                        </div>
                        <div class="panel-body small">
                            {{ object.bio }}
                        </div>
                    </div>
                    {% if user.id == object.user.id %}
                    <button type="button" class="btn btn-outline-secondary btn-block">
                      <a href="{% url 'profile_edit' user.nick_name %}">
                        編集
                      </a>
                    </button>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <h3>
                投稿一覧
            </h3>
            <div class="row">
                {% for blog in blog_list %}
                <div class="col-md-8">
                    <blockquote class="blockquote">
                        <div class="post-preview">
                            <a href="{% url 'detail' blog.id %}">
                                <h3 class="post-meta">
                                    {{blog.content}}
                                </h3>
                            </a>
                            {# timesinceは”|”で渡されたdateから現在までを計算するDjangoの組み込み関数 #}
                            <p class="post-meta">
                                {{blog.posted_date}} ｜投稿から {{blog.posted_date|timesince}}
                            </p>
                        </div>

                    </blockquote>
                </div>
                <div class="col-md-4">
                    {% if blog.photo %}
                    <img src="{{ blog.photo.url }}" class="img-responsive">
                    {% else %}
                    ※画像なし
                    {% endif %}
                </div>
                <br>
                {% endfor %}
            </div>
        </div>
    </div>
</div>


{% endblock %}

microblog/blog/templates/blog/profile_edit.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block body %}
<h1>プロフィール編集</h1>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-9">
            <form method="post" enctype="multipart/form-data">
                <div class="form-group">
                    {% csrf_token %}
                    <div class="col-sm-12">
                        {{ form.as_p }}
                        {{formset.as_p}}
                    </div>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-info"> 更新する</button>
                        <div class="delete-help">一度アカウントを削除すると、二度と元に戻せません。</div>
                        <a data-confirm="本当に削除してもよろしいですか？" class="btn btn-danger"
                           href="{% url 'user_delete' user.nick_name %}">アカウントを削除する</a>
                    </div>
                </div>
            </form>
        </div>
    </div>


    {% endblock %}